ingress: https://arbeid.dev.nav.no/arbeid/dagpenger/soknad-veileder
basePath: /arbeid/dagpenger/soknad-veileder
dekorator:
  url: https://dekoratoren.dev.nav.no/
  env: dev
loginserviceUrl: https://loginservice.dev.nav.no/login
amplitude:
  apiKey: 2f190e67f31d7e4719c5ff048ad3d3e6