ingress: https://www.nav.no/arbeid/dagpenger/soknad-veileder
basePath: /arbeid/dagpenger/soknad-veileder
dekorator:
  url: https://www.nav.no/dekoratoren
  env: prod
loginserviceUrl: https://loginservice.nav.no/login
amplitude:
  apiKey: 913768927b84cde5eac0d0d18c737561
