name: Init Project

on: create

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    - name: Create Next App
      run: |
        npx -y create-next-app --ts app
        cp app/* .
        mkdir src
        mv pages styles src

    - uses: actions/checkout@v2

    - name: Set up ESLint
      run: |
        npm i -D eslint-plugin-jest-dom eslint-plugin-testing-library @typescript-eslint/eslint-plugin
        # Add lint script in package.json

    - name: Set up test suite with Jest, React Testing Library, and Axe
      run: |
        npm i -D @types/jest jest @testing-library/react jest-axe @types/jest-axe
        # Add test script in package.json

    - name: Git Commit/Push Changes
      #uses: actions-x/commit@v1
